### ISSUE TITLE
Add eslint

### ISSUE THREAD

**Issue by 12joan** [12joan/twitter-client#20]
Ideally, the eslint config should be more or less compatible with the current coding style. Semicolons, trailing commas, `'` strings, etc.

The `.github/workflows/push.yml` workflow should look something like this:

```yml
# ...
jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: yarn install --frozen-lockfile
    - run: yarn lint

  deploy_production:
    needs: test
    # ...
```
